apiVersion: v1
kind: Service
metadata:
  name: example-hotrod
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.1.84
  selector:
    app: example-hotrod
