{
 "title": "MYSQL 샘플 데이터를 기반으로 만든 대시보드",
 "time": { "from": "1952-02-01T00:00:00.000Z", "to": "1965-02-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "사내 직군 통계",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT b.title, count(1) FROM employees.employees a inner join employees.titles b on a.emp_no=b.emp_no group by b.title limit 1000;"
    }
   ]
  },
  {
   "title": "사내 팀 별 인원 통계",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT b.dept_name,count(b.dept_name) FROM employees.current_dept_emp a inner join employees.departments b on a.dept_no = b.dept_no group by b.dept_name limit 1000;"
    }
   ]
  },
  {
   "title": "사원 정보",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT a.emp_no as '사원번호', b.title as '직책', concat(first_name,' ',last_name) as '이름'  FROM employees.employees a inner join employees.titles b on a.emp_no=b.emp_no limit 1000;"
    }
   ]
  }
 ]
}