{
 "title": "ch9.7.프로메테우스 스택에서 추가로 제공하는 메트릭을 활용해서 대시보드 그리기",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "etcd cluster 정보",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "etcd_cluster_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "kube-proxy iptable 규칙 개수 (filter)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubeproxy_sync_proxy_rules_iptables_total{table=\"filter\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-proxy iptable 규칙 개수 (nat)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubeproxy_sync_proxy_rules_iptables_total{table=\"nat\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "쿠버네티스 클러스터 스케줄링 정보",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(scheduler_pending_pods) by (queue)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}