apiVersion: v1
kind: Service
metadata:
  name: jaeger-frontend
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    protocol: "TCP"
    targetPort: 16686
    type: LoadBalancer
    loadBalancerIP: 192.168.1.13