{
 "title": "ch4.[Stable] 그라파나에서 자주 사용되는 패널",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "쿠버네티스 노드 정보",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "노드 별 메모리 사용률",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 별 1분 간 CPU의 평균 사용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "important-front의 파드 수 ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"important-front\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네임스페이스 별 컨피그맵 갯수",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count(kube_configmap_info) by (namespace) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 별 5분간 네트워크 수신 변화율",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}