apiVersion: v1
kind: Service
metadata:
  # we doesn't use name jaeger-agent caused by kubernetes port setting issue has been jaeger community
  # if your has wondering on this is issue. please take a look 
  # https://github.com/jaegertracing/jaeger/issues/1986
  # https://github.com/jaegertracing/jaeger-operator/issues/1158
  name: jaeger-ingest
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
  - port: 6831
    protocol: "UDP"
    targetPort: 6831
