apiVersion: v1
kind: Service
metadata:
  name: jaeger-frontend
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    protocol: "TCP"
    targetPort: 16686
  type: LoadBalancer
