apiVersion: v1
kind: Service
metadata:
  name: example-hotrod
  namespace: example-hotrod
spec:
  ports:
  - name: frontend
    port: 8080
    targetPort: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.1.45
  selector:
    app: example-hotrod