{
 "title": "ch6.[Stable] 구체적인 목적을 가지고 사용되는 패널 (optional)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "nginx 에러 로그",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"nginx\"} |= \"error\""
    }
   ]
  },
  {
   "title": " p95에 해당하는 etcd 조회 요청 응답 시간",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(etcd_request_duration_seconds_bucket{operation=\"get\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "프로메테우스 수집 결과",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_targets",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "apiserver 요청 응답 시간",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "default 네임스페이스의 디플로이먼트 상태",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"default\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "워커 노드 별 1분간 CPU의 사용 변화율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", node!=\"m-k8s\"}[1m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}