{
 "title": "ch9.2.그라파나 5장 대시보드에 아코디언(row) 형태의 패널 추가",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "쿠버네티스 노드 별 자원 정보",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드 별 5분간 네트워크 수신 변화율",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "노드 별 1분 간 CPU의 평균 사용률",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - (avg by (node) \t(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "노드 별 메모리 사용률",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "쿠버네티스 기타 정보",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "네임스페이스 별 컨피그맵 갯수",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(kube_configmap_info) by (namespace) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "important-front의 파드 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{deployment=\"important-front\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "쿠버네티스 노드 정보",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "kube_node_info", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}