apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx
  name: nginx-config
data:
  site.conf.template: |
      server {
        charset utf-8;
        listen ${PORT};

        access_log /var/log/nginx/access.log;
          
        location / {
          add_header Content-Type text/html;

          return 200 '<html><body><h1>nginx $hostname\n</h1></body></html>';
        }

        location /error {
          add_header Content-Type text/html;

          return 200 '<html><body><h1>500 Bad Gateway\n</h1></body></html>';
        }
      }