apiVersion: v1
kind: Service
metadata:
  labels:
    app: unschedulable
  name: unschedulable
spec:
  selector:
    app: unschedulable
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unschedulable
  name: unschedulable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unschedulable
  template:
    metadata:
      labels:
        app: unschedulable
    spec:
      nodeSelector:
        kubernetes.io/hostname: m-k8s
      containers:
      - image: nginx:stable
        name: unschedulable